language: node_js

env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=20hiddensecrets

dist: trusty

node_js:
  "stable"

services:
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - npm run testdb:migrate
  - npm install codeclimate-test-reporter -g
  - npm install

script:
  - npm run test

after_success:
  - npm run testdb:migrate
  - npm run coveralls

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
